development:
  adapter: postgresql
  encoding: unicode
  database: login_songs_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: login_songs_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: login_songs_production
  pool: 5
